# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4e7a08173d29a17cf82ceb9c2a947fd32162172932284475e3d89a3f66f6e8b2d64b1f4260058865d7839cf98b3e3916702f915f392daf7ea00701ae792a965

test:
  secret_key_base: 9e21f2b6d9e55fcaefee4af2d43f4b63eeac3b6a6a0a8b0eab6fdc0e278d561187bde3053b2e4fdbf4a0db2c7475bbc1755b457b5af51fe6fb87385b3400e120

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
